// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: service/examples/pkg/proto/echo.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Echo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    //
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` //
}

func (x *Echo) Reset() {
	*x = Echo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_examples_pkg_proto_echo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_service_examples_pkg_proto_echo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_service_examples_pkg_proto_echo_proto_rawDescGZIP(), []int{0}
}

func (x *Echo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Echo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FetchEchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //
}

func (x *FetchEchoRequest) Reset() {
	*x = FetchEchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_examples_pkg_proto_echo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchEchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchEchoRequest) ProtoMessage() {}

func (x *FetchEchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_examples_pkg_proto_echo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchEchoRequest.ProtoReflect.Descriptor instead.
func (*FetchEchoRequest) Descriptor() ([]byte, []int) {
	return file_service_examples_pkg_proto_echo_proto_rawDescGZIP(), []int{1}
}

func (x *FetchEchoRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Data  []*Echo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_examples_pkg_proto_echo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_examples_pkg_proto_echo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_service_examples_pkg_proto_echo_proto_rawDescGZIP(), []int{2}
}

func (x *EchoResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *EchoResponse) GetData() []*Echo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_service_examples_pkg_proto_echo_proto protoreflect.FileDescriptor

var file_service_examples_pkg_proto_echo_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x63, 0x68,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x67, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b,
	0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x2a, 0x0a, 0x04,
	0x45, 0x63, 0x68, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x0c,
	0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x6f, 0x2e, 0x70, 0x61, 0x72, 0x6b, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x42, 0x1c, 0x5a, 0x1a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_examples_pkg_proto_echo_proto_rawDescOnce sync.Once
	file_service_examples_pkg_proto_echo_proto_rawDescData = file_service_examples_pkg_proto_echo_proto_rawDesc
)

func file_service_examples_pkg_proto_echo_proto_rawDescGZIP() []byte {
	file_service_examples_pkg_proto_echo_proto_rawDescOnce.Do(func() {
		file_service_examples_pkg_proto_echo_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_examples_pkg_proto_echo_proto_rawDescData)
	})
	return file_service_examples_pkg_proto_echo_proto_rawDescData
}

var file_service_examples_pkg_proto_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_examples_pkg_proto_echo_proto_goTypes = []interface{}{
	(*Echo)(nil),             // 0: go.park.examples.v1.Echo
	(*FetchEchoRequest)(nil), // 1: go.park.examples.v1.FetchEchoRequest
	(*EchoResponse)(nil),     // 2: go.park.examples.v1.EchoResponse
}
var file_service_examples_pkg_proto_echo_proto_depIdxs = []int32{
	0, // 0: go.park.examples.v1.EchoResponse.data:type_name -> go.park.examples.v1.Echo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_examples_pkg_proto_echo_proto_init() }
func file_service_examples_pkg_proto_echo_proto_init() {
	if File_service_examples_pkg_proto_echo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_examples_pkg_proto_echo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Echo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_examples_pkg_proto_echo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchEchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_examples_pkg_proto_echo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_examples_pkg_proto_echo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_examples_pkg_proto_echo_proto_goTypes,
		DependencyIndexes: file_service_examples_pkg_proto_echo_proto_depIdxs,
		MessageInfos:      file_service_examples_pkg_proto_echo_proto_msgTypes,
	}.Build()
	File_service_examples_pkg_proto_echo_proto = out.File
	file_service_examples_pkg_proto_echo_proto_rawDesc = nil
	file_service_examples_pkg_proto_echo_proto_goTypes = nil
	file_service_examples_pkg_proto_echo_proto_depIdxs = nil
}
